### ISSUE TITLE
DS&P | Exercise 1

### ISSUE THREAD

**Issue by MaximKozlyuk** [MaximKozlyuk/ITMO_DigitalCulture#1]
[Упражнение](https://courses.openedu.ru/courses/course-v1:ITMOUniversity+DATAN+fall_2020_ITMO/courseware/d48bff6430f94d90838f506c005375e9/ea3d64d6bfdd46cfa2021146d026d103/1?activate_block_id=block-v1%3AITMOUniversity%2BDATAN%2Bfall_2020_ITMO%2Btype%40vertical%2Bblock%40340d542f64af4aa897393605516ab413)

**Comment by Vladf8** [comment]
[Сделал](https://github.com/MaximKozlyuk/ITMO_DigitalCulture/blob/master/courses/data_storage_and_processing/exercise1/task1.py), прошу обратить внимание, что csv файл открываю в формате windows-1251.
